In [1]:
import numpy as np

def latlon_to_xyz(lat, lon, radius=6371):
    """
    将经纬度转换为三维笛卡尔坐标系
    
    参数:
    lat: 纬度(度)
    lon: 经度(度)
    radius: 地球半径(km)，默认6371km
    
    返回:
    x, y, z: 三维坐标值(km)
    """
    # 将角度转换为弧度
    lat_rad = np.radians(lat)
    lon_rad = np.radians(lon)
    
    # 计算三维坐标
    x = radius * np.cos(lat_rad) * np.cos(lon_rad)
    y = radius * np.cos(lat_rad) * np.sin(lon_rad)
    z = radius * np.sin(lat_rad)
    
    return x, y, z

# 示例使用
lat1 = 40.1097
lon1 = -88.2042 

x1, y1, z1 = latlon_to_xyz(lat, lon)
print(f"经纬度({lat1}, {lon2})转换为笛卡尔坐标系:")
print(f"X: {x:.2f} km")
print(f"Y: {y:.2f} km")
print(f"Z: {z:.2f} km")
P1 = np.array([x,y,z])

lat2 = 28.6100
lon2 = 77.23

x2, y2, z2 = latlon_to_xyz(lat2, lon2)
print(f"经纬度({lat}, {lon})转换为笛卡尔坐标系:")
print(f"X: {x:.2f} km")
print(f"Y: {y:.2f} km")
print(f"Z: {z:.2f} km")
P2 = np.array([x2,y2,z2])

NameError: name 'lat' is not defined

In [3]:
np.radians(360)

6.283185307179586

In [5]:
90-40.1097

49.8903

In [7]:
90 - 28.61

61.39

In [15]:
import math as m
def R(x):
    p = float(x) * m.pi / 180
    return p

In [17]:
R(49.8903)

0.870749999807727

In [19]:
R(-88.2042)


-1.5394537040875822

In [49]:
R(61.39)

1.0714576277993189

In [51]:
R(77.23)

1.3479177813152208

In [92]:
def f(R,theta,phi):
    return np.array([R * m.sin(phi) * m.cos(theta), R * m.sin(phi) * m.sin(theta), R * m.cos(phi)])

In [94]:
A = f(6371,-1.5394537040875822,0.870749999807727)

In [96]:
B = f(6371,1.3479177813152208,1.0714576277993189)

In [98]:
C = np.cross(A,B)
D = np.cross(C,A)
D = D / np.linalg.norm(D)
print(D)

[0.21515325 0.6332811  0.74341383]


In [59]:
theta = m.acos(np.dot(A,B)/(np.linalg.norm(A))**2)

In [61]:
theta

1.9191499656053517

In [63]:
theta * 6371

12226.904430871695

In [65]:
np.linalg.norm(A-B)

10435.032083483085

In [76]:
C = np.cross(A,B)
beta = m.acos((np.dot(C,np.array([0,0,1])) / np.linalg.norm(C)))

In [80]:
beta * 180 / m.pi

79.65067939284346

In [82]:
C

array([-37246940.8700627 ,   4608550.52519991,   6853911.43449354])

In [84]:
Bpro = np.dot(A,B) / (np.linalg.norm(A))**2 * A

In [88]:
(B - Bpro) / np.linalg.norm(B-Bpro)

array([0.21515325, 0.6332811 , 0.74341383])

In [90]:
def C(x,y,z):
    theta = -1.54
    phi = 0.87
    er = m.cos(theta) * m.sin(phi) * x + m.sin(theta) * m.sin(phi) * y + m.cos(k)
    etheta = -m.sin(theta) * x + m.cos(theta) * y
    ephi = m.cos(theta) * m.cos(phi) * x + m.sin(theta) * m.cos(phi) * y - m.sin(phi) * z
    return np.array([er,etheta,ephi])

In [126]:
A = f(6371,-1.5394537040875822,0.870749999807727)
B = f(6371,1.3479177813152208,1.0714576277993189)
C = np.cross(A,B)
C = C / np.linalg.norm(C)
D = np.cross(C,A)
D = D / np.linalg.norm(D)
print(D)
A = A / np.linalg.norm(A)
Q = np.cross(A,np.array([0,0,1]))
QQ = np.cross(Q,A)
QQ = QQ / np.linalg.norm(QQ)
N = np.array([0,0,1]) - QQ
print(N)
N = N / np.linalg.norm(N)
theta = m.acos(np.dot(D,QQ))
theta = theta * 180 / m.pi
print(theta)

[0.21515325 0.6332811  0.74341383]
[ 0.02018928 -0.6439367   0.23518766]
13.585317000372632


In [2]:
365 / 28

13.035714285714286